### ISSUE TITLE
Clockwise / counterclockwise regions

### ISSUE THREAD

**Issue by caywen** [pchalamet/NPolyBool#1]
Hi there, was playing around with your port of polybool.js and overall works great. However, I think there's a possible bug:

Consider this case:

            var pb = new PolyBool.PolyBool();
            var regions = new List<PolyBool.Region>();
            
            var points = new List<PolyBool.Point>();
            points.Add(new PolyBool.Point(10, 10));
            points.Add(new PolyBool.Point(20, 10));
            points.Add(new PolyBool.Point(20, 20));
            points.Add(new PolyBool.Point(10, 20));
            points.Add(new PolyBool.Point(10, 10));
            regions.Add(new PolyBool.Region(points.ToArray()));
            var polygon = new PolyBool.Polygon(regions.ToArray(), false);

            var regions2 = new List<PolyBool.Region>();
            var points2 = new List<PolyBool.Point>();
            points2.Add(new PolyBool.Point(12, 12));
            points2.Add(new PolyBool.Point(18, 12));
            points2.Add(new PolyBool.Point(18, 18));
            points2.Add(new PolyBool.Point(12, 18));
             points2.Add(new PolyBool.Point(12, 12));
            regions2.Add(new PolyBool.Region(points2.ToArray()));
            var poly2 = new PolyBool.Polygon(regions2.ToArray(), false);

            var difference = pb.Difference(polygon, poly2);

There is a big square with a smaller square cut out - basically resulting in a square donut. In the original polybool.js, this results in 2 regions in the resulting polygon. The first one (the outer one) has a counter-clockwise order and the second one (the inner one) has a clockwise order. This way, we can tell that the inner one is subtractive.

In your port, in the above example, the "difference" also has 2 regions, but both are counter-clockwise order.

**Comment by pchalamet** [comment]
Hi @caywen,
Thanks for reporting the issue.

Yes it's pretty strange, I will have a look. This port shall be on par with polybool.js and considering the trivial test case, there is no numeric stability issue.

Maybe introduced by commit 1abfa860be7aa9418811a2ebaa3bd9aa7e15d033 - this is the only difference as far as I remember with polybool.js.

**Comment by pchalamet** [comment]
H @caywen,

I've added non-regression infrastructure to check difference between NPolyBool and PolyBool.js. JS and .net implementation can be tested side by side.

PolyBoolJS/polybool.js is the original polybool.js code (single file without require) - this is the file I used 2 years ago to check discrepancies.

Looks like your case brings same results after testing.
Could you double check please ? If you want to add more unit-tests, you are more than welcomed btw.

Please note tests can only run on Windows x64 (no time). It's a pity but that was the env I was using at this time. NPolyBool can still run on .net core 3.1-5.0 and all arch.

**Comment by caywen** [comment]
Hi Pierre, thanks so much for your reply. I also ran the same case through polyboojs, and you are right – it’s the same result. I think what is going on is that the GeoJSON part of the demo shows internal holes as reverse ordered, but polybool itself doesn’t do that.

In any case, I think I have a workaround. If I difference A and B, then if there are multiple regions, it must logically mean one is the surrounding polygon and the rest are holes. I think polybool seems to always put the surrounding region as the last region in the poly, and the first N-1 regions are the holes.

I very much appreciate your time and help, and thanks again for doing the port!

-Kevin


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pchalamet** [comment]
No problem and anyway, I already had the test infrastructure hanging out somewhere else.
